### ISSUE TITLE
entity.attributeStorageType.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#37]
## Description

Check that an attribute storage type is present

## Priority

- FAIR: Required

## Issues
- should the storage type be from a controlled vocabulary?
- does ISO 19115 have this concept?

## Procedure

- for each attribute that is present, check if a storage type has been specified, i.e. 'string', 'float', 'int'.

**Comment by iamchrisser** [comment]
ISO does have this concept for attribute information documented in a feature catalog as documented in 19110 - Methodology for Feature Cataloging. In FC_Attribute, this is represented in the 'valueType' element. In ISO, this is required for each attribute described, unless the 'listedValue' element is used to enumerate a list of values that are or may be present in the attribute.

**Comment by jeanetteclark** [comment]
I would argue that this check should not be required, especially since this field is meant "for data in a RDBMS (or other data management system) field." Additionally, this check is already a little redundant since "this type will often be a superset of the allowed domain defined in attributeDomain" and there are 3 required checks regarding attributeDomains already (`entity.attributeEnumeratedDomains.present`, `entity.attributeDomain.present`, `entity.attributeMeasurementScale.present`)

**Comment by csjx** [comment]
I'd agree with @jeanetteclark - this is an option storage type field based on the specific system.  For instance, if the  described `attribute` is stored in a PostgreSQL table and can be a large (64-bit) integer, the value here would be `biginteger`.
This sort of system-specific information doesn't seem to promote interoperability.  It would be more useful if the `biginteger` value was semantically annotated and pointed to the concept of a 64-bit integer out in a well known ontology. But barring that level of detail, I'd make this optional.

**Comment by mbjones** [comment]
I fully agree with @jeanetteclark and @csjx.
