### ISSUE TITLE
entity.format.present can look at invalid XPATHS

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-checks#375]
## Description

If the dataFormat is `textFormat`, `formatName` is not a valid child element so the check fails if `textFormat` is used.

Currently this check looks in `/eml/dataset/*/physical/dataFormat//formatName/text()[normalize-space()]`

## Issues

- Ensure that valid XPATHs are included for all `dataFormat` options (textFormat | externallyDefinedFormat | binaryRasterFormat)

## Procedure

I suggest looking for a non-empty `/eml/dataset/*/physical/dataFormat` instead of looking for the `formatName`

**Comment by gothub** [comment]
@jeanetteclark because the check is looking for `formatName`, it will only find entries like `./physical/dataFormat/externallyDefinedFormat/formatName`, since as you pointed out, `formatName` isn't a sub-element of `textFormat` or `binaryRasterFormat`.

I think the problem is that if a `formatName` entry isn't found, then the check fails, which is wrong, as it would fail if only textFormats are present, for example.

So, i'm proposing that the check passes if no `formatNames` are found, or if all formats that are found have a non-proprietary format specified.

**Comment by jeanetteclark** [comment]
For this check (entity.format.present) I think the check should just look for the presence of `/eml/dataset/*/physical/dataFormat` and not in any of the children.

The proprietary stuff is in issue #377

**Comment by gothub** [comment]
Yes, agreed, I'll update the xpath

**Comment by gothub** [comment]
Updated in commit 3d9eccf684d141cb35759920fa9e96c4d154e25c
