### ISSUE TITLE
entity.attributeDefinition.sufficient

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#43]
## Description

Check if each data entity attribute has a definition and the word count is sufficient.

## Priority

- FAIR: Required

## Issues
- should this be added to the FAIR suite?

## Procedure

- for each attribute, check if a definition is also present. If not, then the check fails and the non-compliant attributes are listed.
- for each attribute definition, check if the word count > 4 words.

**Comment by kstocks** [comment]
A link to a definition in an external resource should also pass.

**Comment by kaiiam** [comment]
@amilan17 @Spin45  @pbuttigieg and others contributing in following discussion:

How does the check know where the definition is? 

@kkelly51 Checking if the definition is there or if there is a n entity attribute definition present?

**Comment by kkelly51** [comment]
"Timestamp in DD:MM:YY format" wouldn't be a valid definition by this description. > 4 words seems arbitrary

**Comment by amruelama** [comment]
Check if the definition has a source link

**Comment by mbjones** [comment]
@kkelly51 Fair enough on the 4 word check being arbitrary.  I agree. 

But I would also note that I don't think ""Timestamp in DD:MM:YY format" is a sufficient description because it omits what the timestamp applies to -- is it the time of the observation, the time the observation was recorded, the time a QA check was run, or some other timestamp?  Many records have multiple timestamps that need to be differentiated.  So I would like to see attribute definitions include both the name of the property being measured, and the name of the entity on which it was measured, and the context of the measurement.  Inn your example, something like "Date on which observation was made in DD:MM:YY format", contrasted with "Date on which observation was entered in data system in DD:MM:YY format".

@kaiiam "How does the check know where the definition is?" -- That would be part of the metadig engine's role to provide each check with the content that is available, which is extracted from the metadata documents available to the check engine.

**Comment by JEDamerow** [comment]
Same as #118 ?
