### ISSUE TITLE
Resource Project Title Controlled check is reporting warnings incorrectly

### ISSUE THREAD

**Issue by mburrus** [NCEAS/metadig-checks#440]
## Description
This existing check verifies that the project is contained in a list of known projects ("Resource Project Title Controlled"). This check is not working correctly on ESS-DIVE.

The "Resource Project Title Controlled" check is unreliable and failing to correctly validate the project information metadata on ESS-DIVE datasets. The check will sometimes issue a warning when the project title is in fact in our controlled list of projects. 

The assessment report should be validating ESS-DIVE dataset project information against the project metadata stored in our new Mule service (https://mule.ess-dive.lbl.gov/api/project/). We started using this service on production around November 2022 and as of May 2023 it is a requirement for all new datasets to select their project metadata from our CV. Yet new datasets are failing this check.

**Examples**
Please compare the project title and PI info in these datasets to ESS-DIVE's project list (https://data.ess-dive.lbl.gov/projects) or directly on Mule (https://mule.ess-dive.lbl.gov/api/project/) to confirm observations: 
- Failed check, yet the project "COMPASS-FME" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-120a44f1c8a626c-20230613T214727898
- Failed check, yet the project "Interdisciplinary Research for Arctic Coastal Environments (InteRFACE)" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-3dde9a8081b3010-20230504T211539774475

From what I found, all datasets with these project titles were incorrectly failing this check.

## Priority

- FAIR: Required 

The current priority says optional, but we may need to change it to required? Confirm with ESS-DIVE team.

**Comment by mbjones** [comment]
@mburrus Thanks for the report. The check was implemented before the Mule service was completed, and so instead it was configured to work against a json file (https://data.ess-dive.lbl.gov/js/themes/ess-dive/data/projects.json) of the projects. See discussion in https://github.com/NCEAS/metadig-checks/issues/420 as it was implemented. Now that you have the projects service working, the check should be updated to pull from there, but that will take some time. @jeanetteclark is getting ready to do a new MetaDIG release, so right now is a good time to try to patch in a change to the test. I see two potential paths with different levels of work:

- Simple: copy a new version of the json file with updated projects into place and use it -- fast and easy, no code changes, doesn't solve the long term problem, but could probably be done very quickly
- More complex: recode the test to pull from https://data.ess-dive.lbl.gov/js/themes/ess-dive/data/projects.json (or another Mule URL) each time it is run (I think the data were grabbed once at the beginning) -- this is the better approach for the long term, but will take a little more coding, and will need to be incorporated into a MetaDIG release

One thing I note is that the quality score for datasets might change as this project list changes, but we don't have a way of knowing when the project list changes. Typically, we trigger new suite runs when the dataset is modified in some way, and so we can predict when a suite needs to be rerun for the dataset (e.g., the version of either the data or the suite changes).  We'll need to figure out how to determine when to go back and rerun suites for project list changes. Is the project list versioned, or have another mutability indicator? How can we tell programmatically when data changes there?

cc @vchendrix @taojing2002 @rushirajnenuji

**Comment by vchendrix** [comment]
> @mburrus Thanks for the report. The check was implemented before the Mule service was completed, and so instead it was configured to work against a json file (https://data.ess-dive.lbl.gov/js/themes/ess-dive/data/projects.json) of the projects. See discussion in #420 as it was implemented. Now that you have the projects service working, the check should be updated to pull from there, but that will take some time. @jeanetteclark is getting ready to do a new MetaDIG release, so right now is a good time to try to patch in a change to the test. I see two potential paths with different levels of work:
> 
> * Simple: copy a new version of the json file with updated projects into place and use it -- fast and easy, no code changes, doesn't solve the long term problem, but could probably be done very quickly
> * More complex: recode the test to pull from https://data.ess-dive.lbl.gov/js/themes/ess-dive/data/projects.json (or another Mule URL) each time it is run (I think the data were grabbed once at the beginning) -- this is the better approach for the long term, but will take a little more coding, and will need to be incorporated into a MetaDIG release
> 
> One thing I note is that the quality score for datasets might change as this project list changes, but we don't have a way of knowing when the project list changes. Typically, we trigger new suite runs when the dataset is modified in some way, and so we can predict when a suite needs to be rerun for the dataset (e.g., the version of either the data or the suite changes). We'll need to figure out how to determine when to go back and rerun suites for project list changes. Is the project list versioned, or have another mutability indicator? How can we tell programmatically when data changes there?
> 
> cc @vchendrix @taojing2002 @rushirajnenuji

Ah!  That makes sense. I thought it was implemented to pull from MULE already but I see that there is an issue ticket (#438) for implementing it.  @mburrus  a work around would be to update the projects.json file in ess-dive-catalog.

**Comment by jeanetteclark** [comment]
Updating the check code to pull from a stable version of the file hosted somewhere would be fairly easy. If you need an immediate fix, @mbjones simple solution above sounds fine. I'll make a note over in #420 to update the check and release a new version of the ESS-DIVE suite. This will trigger all of the datasets to be re-run through the new suite, though I am also curious about how best to update datasets with updates to that json file if changes to the file can be made without a new version of the suite.

**Comment by JEDamerow** [comment]
@jeanetteclark We actually now enforce the controlled project name upon submission and have updated all datasets with the controlled project names, so there is really no longer a function for this check. We have decided that we can remove it instead of changing the source.  Does this simplify the course of action or create any problems?

**Comment by jeanetteclark** [comment]
@JEDamerow and I talked on slack, and it sounds like there are a couple of actions to take

- [ ] update the check to pull directly from the ess-dive endpoint: https://mule.ess-dive.lbl.gov/api/project/ (#438)
- [ ] update the check so that it is required
- [ ] release new version of the ess-dive quality suite
- [ ] deploy new version, which will re-run all existing documents to point to the new list

It sounds like it is possible that the project list would be updated, though it would not occur frequently, and it is possible that if a new list were released, previous runs of a dataset would not be accurate with regard to the new list. So @mbjones we would need to discuss what the best strategy is for re-running a suite were an update to the list to occur.

The other path forward is to include the project list in the actual suite release, and any update to the project list would require a new version of the suite. This has the advantage of not having to re-run anything manually (release of the new suite would trigger new runs), and it would make results more reproducible by release version. The disadvantage is that it is probably overall more work to do things this way, especially if project list updates end up becoming common.

**Comment by jeanetteclark** [comment]
As discussed over in #420, this was actually fixed, and the only issue is figuring out how we want to update old datasets to reflect the new project list.

In the long term, we need to develop a mechanism to just re-run some checks periodically. This would likely mean a schema change in the check documents.

In the short term to solve this immediate problem, I can roll back the last harvest date for the ESS-DIVE mn so that all of the content is re-harvested. Thoughts @mbjones?

**Comment by jeanetteclark** [comment]
re-harvested all content today, checks appear to be working as expected
