### ISSUE TITLE
metadata.identifier.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#59]
## Description

Check if a metadata identifier is present and if an identifier type can be determined

## Priority

FAIR: Required

## Issues
- what is the list of identifier types to check?
- many DataONE identifiers do not conform to a well known id type - should the check fail if the type cannot be determined?

## Procedure

- check if a metadata identifier is present, if not then the check fails
- check if an identifier namespace exists that indicates what type of identifier it is, and print a msg if the identifier type cannot be determined

**Comment by tedhabermann** [comment]
The question "should the check fail if the type cannot be determined?" is an interesting one. IMHO, the identifier type should be included. In some cases, the form of the identifier is clearly type dependent. In that case, I invoke the "all obvious stuff should be in the metadata" rule. If the type is there, tools can ask "do you have this kind of identifier" rather than reading the identifier and trying to grok the type.

**Comment by JEDamerow** [comment]
Similar to implemented check #129
