### ISSUE TITLE
resource.date.revision.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#72]
## Description

Check if a dataset publication revision date is specified

## Priority

- FAIR: Optional

## Issues
- for EML, should `./pubDate` be checked  `./maintenance/changeHistory/changeDate` be checked.

## Procedure

- check if the dataset publication revision date is present, and if so, the check passes.

**Comment by tedhabermann** [comment]
The target of this check exists in the DataCite dialect: data.attributes.dates[?(@.dateType="Updated")].date

**Comment by tedhabermann** [comment]
This check makes a resource more FAIR if it has been revised. I think it should be dropped.

**Comment by mbjones** [comment]
I'm not clear on the concept being described here -- its defined ambiguously as 'dataset publication revision date'.  Is that:

- the initial date of publication?
- the date on which a resource was revised (possibly after initially being published)?
- some other date?

Let's revise the Description of this to be clear about which date concept is being checked.

**Comment by JEDamerow** [comment]
I think that this could be a repository level check, to see if revision date is tracked. For example, if a dataset is cited, it is important for new users to know if the data or metadata has changed since that citation. It makes less sense on a dataset level, because many datasets are not revised. 

One purpose/benefit for these checks in general, is to provide a resource for specific things that dataset authors AND repositories can do to help make their datasets more FAIR.
